-- GOS-153 — Saved Addresses (Customer or Professional). See Address's own
-- header comment in prisma/schema.prisma for the full design. Hand-written
-- (not machine-generated by `prisma migrate dev`) because both the local
-- dev database and the isolated test database currently have pre-existing,
-- unrelated drift against migration history on this machine — this
-- migration was authored to match Prisma's own generated SQL conventions
-- exactly (see e.g. 20260911140000_gos_121_add_reviews/migration.sql for
-- the same CreateEnum/CreateTable/AddForeignKey/CHECK shape this mirrors).

-- CreateEnum
CREATE TYPE "AddressOwnerRole" AS ENUM ('CUSTOMER', 'PROFESSIONAL');

-- CreateTable
CREATE TABLE "Address" (
    "id" UUID NOT NULL,
    "ownerRole" "AddressOwnerRole" NOT NULL,
    "customerProfileId" UUID,
    "professionalProfileId" UUID,
    "formattedAddress" TEXT NOT NULL,
    "placeId" TEXT NOT NULL,
    "latitude" DOUBLE PRECISION NOT NULL,
    "longitude" DOUBLE PRECISION NOT NULL,
    "label" TEXT,
    "isDefault" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Address_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "Address_customerProfileId_idx" ON "Address"("customerProfileId");

-- CreateIndex
CREATE INDEX "Address_professionalProfileId_idx" ON "Address"("professionalProfileId");

-- AddForeignKey
ALTER TABLE "Address" ADD CONSTRAINT "Address_customerProfileId_fkey" FOREIGN KEY ("customerProfileId") REFERENCES "CustomerProfile"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Address" ADD CONSTRAINT "Address_professionalProfileId_fkey" FOREIGN KEY ("professionalProfileId") REFERENCES "ProfessionalProfile"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- GOS-153 — structural guardrail, same precedent as
-- `quote_negotiation_message_author_shape_check`/`review_author_shape_check`:
-- makes it physically impossible to persist an Address whose owner-identifying
-- columns don't match its declared ownerRole.
ALTER TABLE "Address" ADD CONSTRAINT "address_owner_shape_check" CHECK (
  (
    "ownerRole" = 'CUSTOMER'
    AND "customerProfileId" IS NOT NULL
    AND "professionalProfileId" IS NULL
  )
  OR (
    "ownerRole" = 'PROFESSIONAL'
    AND "professionalProfileId" IS NOT NULL
    AND "customerProfileId" IS NULL
  )
);

-- GOS-153 — at most ONE Address per owning profile may be the default,
-- enforced physically (not just at the application layer) via two partial
-- unique indexes — one per owner-column, since a single unique index across
-- both nullable columns cannot express "per-owner uniqueness" the way a
-- single non-null owner column could. Same "Prisma cannot express a partial
-- index in schema.prisma, so it is hand-added here" precedent as
-- `PaymentAttempt_engagementId_active_key`
-- (20260918120000_gos_85_card_payment_attempt/migration.sql).
CREATE UNIQUE INDEX "address_customer_default_unique" ON "Address"("customerProfileId") WHERE "isDefault" = true AND "customerProfileId" IS NOT NULL;

-- GOS-153 — see the comment on `address_customer_default_unique` above.
CREATE UNIQUE INDEX "address_professional_default_unique" ON "Address"("professionalProfileId") WHERE "isDefault" = true AND "professionalProfileId" IS NOT NULL;
