-- GOS-157 (story GOS-152) — optional per-specialization operating radius.
-- See ProfessionalSpecialization's header comment in prisma/schema.prisma.
--
-- Hand-written (not machine-generated by `prisma migrate dev`), same reason
-- 20260922200000_gos_155_add_proximity_search/migration.sql documents
-- (pre-existing, unrelated local migration-history drift). Additive,
-- nullable column: NULL = no distance limit, so no backfill is needed.

-- AlterTable
ALTER TABLE "ProfessionalSpecialization" ADD COLUMN     "operatingRadiusKm" INTEGER;
