-- GOS-155 — Proximity search (nearbyProfessionals/nearbyServiceRequests) +
-- addressId on ServiceRequest. See Address's and ServiceRequest's own
-- header comments in prisma/schema.prisma for the full design.
--
-- Hand-written (not machine-generated by `prisma migrate dev`), same reason
-- 20260922120000_gos_153_add_addresses/migration.sql documents: this local
-- dev database currently has pre-existing, unrelated drift against
-- migration history on this machine (`prisma migrate dev` refuses to run,
-- reporting migration
-- `20260903231759_gos_72_media_upload_ref_quote_attachment_message_images`
-- was "modified after it was applied") — this migration was authored to
-- match Prisma's own generated SQL conventions exactly and applied via
-- `prisma migrate deploy` (which does not perform the same drift/shadow-
-- database check `migrate dev` does) instead.

-- AlterTable: ServiceRequest.addressId (nullable — no backfill for
-- ServiceRequests published before this column existed; onDelete SetNull —
-- see the schema's own comment on why this is never Cascade).
ALTER TABLE "ServiceRequest" ADD COLUMN "addressId" UUID;

-- CreateIndex
CREATE INDEX "ServiceRequest_addressId_idx" ON "ServiceRequest"("addressId");

-- AddForeignKey
ALTER TABLE "ServiceRequest" ADD CONSTRAINT "ServiceRequest_addressId_fkey" FOREIGN KEY ("addressId") REFERENCES "Address"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- CreateIndex: supports the bounding-box pre-filter both
-- `ProfilesRepository.findNearbyProfessionals`/
-- `ServiceRequestsRepository.findNearbyCompatible` raw-SQL queries apply
-- before the exact Haversine distance check.
CREATE INDEX "Address_latitude_longitude_idx" ON "Address"("latitude", "longitude");
